// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import BayesometerController from "./bayesometer_controller";
application.register("bayesometer", BayesometerController);

import BinomilatorController from "./binomilator_controller";
application.register("binomilator", BinomilatorController);

import CipherController from "./cipher_controller";
application.register("cipher", CipherController);

import ColoursquareController from "./coloursquare_controller";
application.register("coloursquare", ColoursquareController);

import CursorController from "./cursor_controller";
application.register("cursor", CursorController);

import DeepseekChatController from "./deepseek_chat_controller";
application.register("deepseek-chat", DeepseekChatController);

import DiffractorController from "./diffractor_controller";
application.register("diffractor", DiffractorController);

import DistractionmodeController from "./distractionmode_controller";
application.register("distractionmode", DistractionmodeController);

import DoomCubeController from "./doom_cube_controller";
application.register("doom-cube", DoomCubeController);

import DrawerController from "./drawer_controller";
application.register("drawer", DrawerController);

import EdemoController from "./edemo_controller";
application.register("edemo", EdemoController);

import EncryptorController from "./encryptor_controller";
application.register("encryptor", EncryptorController);

import EyamController from "./eyam_controller";
application.register("eyam", EyamController);

import FactorizerController from "./factorizer_controller";
application.register("factorizer", FactorizerController);

import FgraphController from "./fgraph_controller";
application.register("fgraph", FgraphController);

import ForcesController from "./forces_controller";
application.register("forces", ForcesController);

import GradientorController from "./gradientor_controller";
application.register("gradientor", GradientorController);

import GuitemplateController from "./guitemplate_controller";
application.register("guitemplate", GuitemplateController);

import HarmonographController from "./harmonograph_controller";
application.register("harmonograph", HarmonographController);

import HeadingHighlightController from "./heading_highlight_controller";
application.register("heading-highlight", HeadingHighlightController);

import HlsController from "./hls_controller";
application.register("hls", HlsController);

import InequalityplotterController from "./inequalityplotter_controller";
application.register("inequalityplotter", InequalityplotterController);

import InsultController from "./insult_controller";
application.register("insult", InsultController);

import IntegraController from "./integra_controller";
application.register("integra", IntegraController);

import JuliaController from "./julia_controller";
application.register("julia", JuliaController);

import LocomotiveScrollController from "./locomotive_scroll_controller";
application.register("locomotive-scroll", LocomotiveScrollController);

import MatrixtransformationsController from "./matrixtransformations_controller";
application.register("matrixtransformations", MatrixtransformationsController);

import MomentumController from "./momentum_controller";
application.register("momentum", MomentumController);

import Movie2xytController from "./movie2xyt_controller";
application.register("movie2xyt", Movie2xytController);

import NeudecController from "./neudec_controller";
application.register("neudec", NeudecController);

import NormalstatsController from "./normalstats_controller";
application.register("normalstats", NormalstatsController);

import OnekoController from "./oneko_controller";
application.register("oneko", OnekoController);

import OrbitsController from "./orbits_controller";
application.register("orbits", OrbitsController);

import PoweraidController from "./poweraid_controller";
application.register("poweraid", PoweraidController);

import ProjectileController from "./projectile_controller";
application.register("projectile", ProjectileController);

import ProjectCarouselController from "./project_carousel_controller";
application.register("project-carousel", ProjectCarouselController);

import QuadraticaController from "./quadratica_controller";
application.register("quadratica", QuadraticaController);

import ShmController from "./shm_controller";
application.register("shm", ShmController);

import ShortcutsController from "./shortcuts_controller";
application.register("shortcuts", ShortcutsController);

import SlopeController from "./slope_controller";
application.register("slope", SlopeController);

import SoundanalyserController from "./soundanalyser_controller";
application.register("soundanalyser", SoundanalyserController);

import SoundsnipperController from "./soundsnipper_controller";
application.register("soundsnipper", SoundsnipperController);

import SpheriumController from "./spherium_controller";
application.register("spherium", SpheriumController);

import StandingwavesController from "./standingwaves_controller";
application.register("standingwaves", StandingwavesController);

import TransformerController from "./transformer_controller";
application.register("transformer", TransformerController);

import TrigonometricaController from "./trigonometrica_controller";
application.register("trigonometrica", TrigonometricaController);

import WaveformController from "./waveform_controller";
application.register("waveform", WaveformController);

import WaveformerController from "./waveformer_controller";
application.register("waveformer", WaveformerController);

import TurboMountController from "./turbo_mount_controller";
application.register("turbo-mount", TurboMountController);

import ReactMountController from "./react_mount_controller";
application.register("react-mount", ReactMountController);
